// File generated by the FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9gjodK9pJMo_Iy6yiMuG7WdCm8-xep9A',
    appId: '1:18921283010:web:d27d7e01054a5b', // Estimated, web app id usually differs
    messagingSenderId: '18921283010',
    projectId: 'akumah-33feb',
    authDomain: 'akumah-33feb.firebaseapp.com',
    storageBucket: 'akumah-33feb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9gjodK9pJMo_Iy6yiMuG7WdCm8-xep9A',
    appId: '1:18921283010:android:269512041a273e01054a5b',
    messagingSenderId: '18921283010',
    projectId: 'akumah-33feb',
    storageBucket: 'akumah-33feb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9gjodK9pJMo_Iy6yiMuG7WdCm8-xep9A',
    appId: '1:18921283010:ios:d27d7e01054a5b', // Placeholder
    messagingSenderId: '18921283010',
    projectId: 'akumah-33feb',
    storageBucket: 'akumah-33feb.firebasestorage.app',
    iosBundleId: 'com.Akumah',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9gjodK9pJMo_Iy6yiMuG7WdCm8-xep9A',
    appId: '1:18921283010:ios:d27d7e01054a5b', // Placeholder
    messagingSenderId: '18921283010',
    projectId: 'akumah-33feb',
    storageBucket: 'akumah-33feb.firebasestorage.app',
    iosBundleId: 'com.Akumah',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9gjodK9pJMo_Iy6yiMuG7WdCm8-xep9A',
    appId: '1:18921283010:windows:d27d7e01054a5b', // Placeholder
    messagingSenderId: '18921283010',
    projectId: 'akumah-33feb',
    storageBucket: 'akumah-33feb.firebasestorage.app',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyC9gjodK9pJMo_Iy6yiMuG7WdCm8-xep9A',
    appId: '1:18921283010:linux:d27d7e01054a5b', // Placeholder
    messagingSenderId: '18921283010',
    projectId: 'akumah-33feb',
    storageBucket: 'akumah-33feb.firebasestorage.app',
  );
}
